# The MIT License (MIT)
#
# Copyright (c) 2022-2025 Objectionary.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
name: itest
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: itest-${{ github.ref }}
  cancel-in-progress: true
jobs:
  itest:
    strategy:
      matrix:
        os: [ ubuntu-24.04, macos-15, windows-2022 ]
        java: [ 22 ]
        node: [ 16 ]
        # lang: [Java, JavaScript]
        lang: [ Java ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - run: npm install
      - shell: bash
        run: |
          cd itest
          declare -a opts=(
            "../src/eoc.js"
            "--batch"
            "--language=${{ matrix.lang }}"
            "--easy"
          )
          node "${opts[@]}" link
          node "${opts[@]}" --alone dataize program
          node "${opts[@]}" clean
          node "${opts[@]}" test
